name: server-linux-aws-application

on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  ARCGIS_ONLINE_USERNAME: ${{ secrets.ARCGIS_ONLINE_USERNAME }}
  ARCGIS_ONLINE_PASSWORD: ${{ secrets.ARCGIS_ONLINE_PASSWORD }}
  PYTHONPATH: ${{ github.workspace }}/aws/scripts
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-server-linux/application.tfvars.json

concurrency:
  group: ${{ github.ref_name }}

jobs:
  application:
    name: Configure Applications
    runs-on: ubuntu-latest
    outputs:
      arcgis_server_url: ${{ steps.output.outputs.arcgis_server_url }}
    defaults:
      run:
        working-directory: aws/arcgis-server-linux/application
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Link Config Directory
      id: symlink
      run: ln -s ${{ github.workspace }}/config ~/config
    - name: Install Boto3 and Ansible
      id: install-boto3
      run: |
        pip install boto3
        pip install "ansible>=9.0,<10.0"
    - name: Install Ansible Collections
      id: install-collections
      run: ansible-galaxy collection install ${{ github.workspace }}/ansible_collections/arcgis -p /usr/share/ansible/collections
    - name: Run Terraform 
      id: terraform
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        DEPLOYMENT_ID=$(jq -r '.deployment_id' $CONFIG_FILE)
        terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/application.tfstate" -backend-config="region=$AWS_DEFAULT_REGION"
        terraform apply -var-file $CONFIG_FILE -var=arcgis_online_username=$ARCGIS_ONLINE_USERNAME -var=arcgis_online_password=$ARCGIS_ONLINE_PASSWORD -auto-approve
    - name: Terraform Output
      id: output  
      run: echo arcgis_server_url=$(terraform output arcgis_server_url) >> $GITHUB_OUTPUT
